name: Build and deploy app

on: [push, schedule]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        pip install -U streamlit networkx pyvis
    - run: streamlit run app.py
